language: node_js
notifications:
  email: false
node_js:
  - "7"
cache:
  directories:
    - node_modules
before_install:
    - npm install -g dlvr
script:
  - npm run ci
after_script:
  - dlvr release-ci

